name: Cleanup Repository

on:
  schedule:
    - cron: "0 0 1 1 *" # Exécution automatique chaque 1er janvier
  workflow_dispatch: # Déclencheur manuel

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Unwanted Files
        run: |
          shopt -s extglob
          rm -rf !(annonce|README.md)

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Cleanup repository - Removed all files except 'annonce' and 'README.md'"
          git push
