name: Cleanup Repository

on:
  workflow_dispatch: # Activation manuelle
  schedule:
    - cron: '0 0 1 1 *' # Tous les 1er janvier à minuit UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Delete Unwanted Files
      run: |
        find . -type f ! -name 'README.md' ! -name 'annonce' -delete
        find . -type d -empty -delete
        git add .
        git commit -m "Cleanup repository - Removed all files except 'annonce' and 'README.md'" || echo "No changes to commit"

    - name: Push Changes to GitHub
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
